import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show immutable;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;
import 'package:media_kit/media_kit.dart';
import 'package:path_provider/path_provider.dart';

/// Immutable request describing one thumbnail to fetch/decode.
@immutable
class ThumbRequest {
  const ThumbRequest({
    required this.url,
    required this.headers,
    required this.cacheKey,
    this.size = 256,
    this.isVideo = false,
  });

  final String url;
  final Map<String, String> headers;
  final String cacheKey;
  final int size;

  /// When true, the thumbnail is generated by capturing a video keyframe
  /// (via libmpv) instead of decoding image bytes.
  final bool isVideo;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbRequest && other.cacheKey == cacheKey && other.size == size;

  @override
  int get hashCode => Object.hash(cacheKey, size);
}

/// Stable cache key: sha1 hex of `fs|path|modTime|size|px` (modTime ISO, or
/// empty when unknown). A change to any component invalidates the cached thumb.
String thumbCacheKey(
  String fs,
  String path,
  DateTime? modTime,
  int size,
  int px,
) {
  final mt = modTime?.toIso8601String() ?? '';
  final raw = '$fs|$path|$mt|$size|$px';
  return sha1.convert(utf8.encode(raw)).toString();
}

/// Lazy, disk-cached thumbnail loader with bounded concurrency + in-flight dedup.
/// Images decode from bytes; videos capture a keyframe via libmpv (media_kit).
class ThumbnailService {
  ThumbnailService();

  static const int _maxConcurrent = 4;

  int _active = 0;
  final _waiters = <Completer<void>>[];
  final _inFlight = <String, Future<Uint8List?>>{};

  Directory? _cacheDir;

  /// Load thumbnail bytes (PNG) for [req]; null on any failure.
  Future<Uint8List?> load(ThumbRequest req) async {
    // 1) Disk cache.
    try {
      final dir = await _ensureDir();
      final file = File('${dir.path}/${req.cacheKey}.png');
      if (await file.exists()) {
        return await file.readAsBytes();
      }
    } catch (_) {
      // fall through to generation
    }

    // 2) In-flight dedup keyed by cacheKey.
    final existing = _inFlight[req.cacheKey];
    if (existing != null) return existing;

    final future = _generate(req);
    _inFlight[req.cacheKey] = future;
    try {
      return await future;
    } finally {
      _inFlight.remove(req.cacheKey);
    }
  }

  Future<Uint8List?> _generate(ThumbRequest req) async {
    await _acquire();
    try {
      return req.isVideo
          ? await _captureVideoFrame(req)
          : await _fetchAndDecodeImage(req);
    } finally {
      _release();
    }
  }

  Future<Uint8List?> _fetchAndDecodeImage(ThumbRequest req) async {
    try {
      final resp = await http
          .get(Uri.parse(req.url), headers: req.headers)
          .timeout(const Duration(seconds: 20));
      if (resp.statusCode < 200 || resp.statusCode >= 300) return null;
      return _downscaleAndCache(resp.bodyBytes, req);
    } catch (_) {
      return null;
    }
  }

  /// Open the video headlessly, wait for the first decoded frame, and screenshot
  /// it via libmpv. Falls back to null (→ kind icon) on any failure/timeout.
  Future<Uint8List?> _captureVideoFrame(ThumbRequest req) async {
    Player? player;
    try {
      player = Player();
      await player.open(Media(req.url, httpHeaders: req.headers), play: false);
      // Wait until libmpv reports a non-zero video size (a frame is decoded).
      await player.stream.width
          .firstWhere((w) => (w ?? 0) > 0)
          .timeout(const Duration(seconds: 12));
      final raw = await player
          .screenshot(format: 'image/png')
          .timeout(const Duration(seconds: 6));
      if (raw == null) return null;
      return _downscaleAndCache(raw, req);
    } catch (_) {
      return null;
    } finally {
      try {
        await player?.dispose();
      } catch (_) {
        // already disposed / never constructed
      }
    }
  }

  /// Downscale [bytes] to [ThumbRequest.size] px wide WebP/PNG and write the cache.
  Future<Uint8List?> _downscaleAndCache(
    Uint8List bytes,
    ThumbRequest req,
  ) async {
    try {
      final codec = await ui.instantiateImageCodec(
        bytes,
        targetWidth: req.size,
      );
      final frame = await codec.getNextFrame();
      final data = await frame.image.toByteData(format: ui.ImageByteFormat.png);
      if (data == null) return null;
      final png = data.buffer.asUint8List();
      try {
        final dir = await _ensureDir();
        await File(
          '${dir.path}/${req.cacheKey}.png',
        ).writeAsBytes(png, flush: true);
      } catch (_) {
        // cache write best-effort
      }
      return png;
    } catch (_) {
      return null;
    }
  }

  Future<Directory> _ensureDir() async {
    final cached = _cacheDir;
    if (cached != null) return cached;
    Directory base;
    try {
      base = await getApplicationCacheDirectory();
    } catch (_) {
      base = await getTemporaryDirectory();
    }
    final dir = Directory('${base.path}/airclone_thumbs');
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    _cacheDir = dir;
    return dir;
  }

  Future<void> _acquire() async {
    if (_active < _maxConcurrent) {
      _active++;
      return;
    }
    final c = Completer<void>();
    _waiters.add(c);
    await c.future;
    _active++;
  }

  void _release() {
    _active--;
    if (_waiters.isNotEmpty) {
      final c = _waiters.removeAt(0);
      if (!c.isCompleted) c.complete();
    }
  }
}

/// Provides the singleton [ThumbnailService].
final thumbnailServiceProvider = Provider<ThumbnailService>(
  (ref) => ThumbnailService(),
);
