import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show immutable;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:path_provider/path_provider.dart';

import 'android_native.dart';
import 'cache_crypto.dart';

/// Immutable request describing one thumbnail to fetch/decode.
@immutable
class ThumbRequest {
  const ThumbRequest({
    required this.url,
    required this.headers,
    required this.cacheKey,
    this.cacheSecret = '',
    this.size = 256,
    this.isVideo = false,
  });

  final String url;
  final Map<String, String> headers;
  final String cacheKey;

  /// Per-remote secret seed for the at-rest cache key when the config has no
  /// password (typically the remote name). Ignored when a config password is set.
  final String cacheSecret;

  final int size;

  /// When true, the thumbnail is generated by capturing a video keyframe
  /// (via libmpv) instead of decoding image bytes.
  final bool isVideo;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbRequest && other.cacheKey == cacheKey && other.size == size;

  @override
  int get hashCode => Object.hash(cacheKey, size);
}

/// How much luma may vary across a captured frame before it counts as a real
/// picture. Kept in step with the same check in MainActivity.kt, which uses it
/// to choose between candidate frames.
const int kBlankLumaRange = 12;

/// True when [rgba] (packed RGBA, 4 bytes per pixel) is one flat shade — the
/// black leader a video opens on, or a frame that never actually decoded.
/// Caching one of those looks to the user like a permanently broken thumbnail,
/// so the capture path treats it as a failure instead.
///
/// Pure so the threshold is unit-tested without a codec. Empty input is not
/// "flat": there is nothing to judge.
bool isFlatRgba(Uint8List rgba, {int range = kBlankLumaRange}) {
  if (rgba.length < 4) return false;
  var min = 255;
  var max = 0;
  for (var i = 0; i + 3 < rgba.length; i += 4) {
    // Integer luma (BT.601 weights ×256) — this runs over every pixel of a
    // thumbnail, so it stays in ints.
    final luma = (rgba[i] * 77 + rgba[i + 1] * 150 + rgba[i + 2] * 29) >> 8;
    if (luma < min) min = luma;
    if (luma > max) max = luma;
    if (max - min > range) return false;
  }
  return true;
}

/// Stable cache key: sha1 hex of `fs|path|modTime|size|px` (modTime ISO, or
/// empty when unknown). A change to any component invalidates the cached thumb.
String thumbCacheKey(
  String fs,
  String path,
  DateTime? modTime,
  int size,
  int px,
) {
  final mt = modTime?.toIso8601String() ?? '';
  final raw = '$fs|$path|$mt|$size|$px';
  return sha1.convert(utf8.encode(raw)).toString();
}

/// Lazy, **encrypted**, disk-cached thumbnail loader with bounded concurrency +
/// in-flight dedup. Images decode from bytes; videos capture a keyframe via
/// libmpv (media_kit). Cache blobs are AES-GCM sealed via [CacheCrypto]; with
/// memory-only mode on, nothing touches disk.
class ThumbnailService {
  ThumbnailService(this._ref);

  final Ref _ref;

  static const int _maxConcurrent = 4;

  /// Video keyframes are FAR heavier than image decodes: each one spins up a
  /// whole libmpv [Player] that streams and decodes real media. On a phone,
  /// several of those at once starve the player the user is actually watching
  /// (the reason cloud video previews felt unreliable on Android), so mobile
  /// captures them strictly one at a time. Desktop can afford two.
  ///
  /// Android is the exception now that it uses the platform frame grabber
  /// instead of libmpv: nothing there competes with playback, so a folder of
  /// videos doesn't have to fill in single file.
  static final int _maxConcurrentVideo = Platform.isAndroid
      ? 2
      : (_isMobile ? 1 : 2);

  /// First-frame budget for a keyframe capture. Mobile gets far longer: the
  /// bytes come from a cloud backend over a phone connection, and a capture
  /// that times out costs the same work again on the next scroll.
  static final Duration _videoFirstFrameTimeout = _isMobile
      ? const Duration(seconds: 30)
      : const Duration(seconds: 12);

  static final bool _isMobile = Platform.isAndroid || Platform.isIOS;

  int _active = 0;
  final _waiters = <Completer<void>>[];

  /// Second gate, held only by video captures and always taken BEFORE the
  /// general one — images never take it, so the ordering can't deadlock.
  int _activeVideo = 0;
  final _videoWaiters = <Completer<void>>[];

  final _inFlight = <String, Future<Uint8List?>>{};

  /// Cache keys whose bytes downloaded fine but could NOT be turned into a
  /// picture — a HEIC/SVG that passes `isThumbnailable` yet Flutter's image
  /// codec rejects, or a video whose frames are blank. This is a PERMANENT
  /// failure, not a transient one — recorded so the retry loop and every scroll
  /// re-mount don't re-download a multi-MB original that will never render.
  /// Session-scoped; a forced rebuild clears + re-attempts.
  final _undecodable = <String>{};

  Directory? _cacheDir;

  /// Load thumbnail bytes (PNG) for [req]; null on any failure. When [force] is
  /// set the disk cache is bypassed (and later overwritten) so a stale or
  /// corrupt cached thumbnail is regenerated from source.
  Future<Uint8List?> load(ThumbRequest req, {bool force = false}) async {
    final memoryOnly = _ref.read(cacheMemoryOnlyProvider);

    // A known-undecodable file: don't re-download it. A forced rebuild clears
    // the mark so the user can re-attempt (e.g. after adding codec support).
    if (force) {
      _undecodable.remove(req.cacheKey);
    } else if (_undecodable.contains(req.cacheKey)) {
      return null;
    }

    // 1) Encrypted disk cache (skipped on a forced rebuild).
    if (!memoryOnly && !force) {
      try {
        final dir = await _ensureDir();
        final file = File('${dir.path}/${req.cacheKey}.bin');
        if (await file.exists()) {
          final blob = await file.readAsBytes();
          final png = await _ref
              .read(cacheCryptoProvider)
              .open(blob, req.cacheSecret);
          if (png != null) return png; // miss/corrupt → regenerate below
        }
      } catch (_) {
        // fall through to generation
      }
    }

    // 2) In-flight dedup keyed by cacheKey.
    final existing = _inFlight[req.cacheKey];
    if (existing != null) return existing;

    final future = _generateAndCache(req, memoryOnly);
    _inFlight[req.cacheKey] = future;
    try {
      return await future;
    } finally {
      _inFlight.remove(req.cacheKey);
    }
  }

  Future<Uint8List?> _generateAndCache(
    ThumbRequest req,
    bool memoryOnly,
  ) async {
    // Videos hold BOTH gates for the whole capture; images only the general one.
    if (req.isVideo) await _acquireVideo();
    await _acquire();
    Uint8List? png;
    try {
      png = req.isVideo
          ? await _captureVideoFrame(req)
          : await _fetchAndDecodeImage(req);
    } finally {
      _release();
      if (req.isVideo) _releaseVideo();
    }
    if (png == null) return null;

    if (!memoryOnly) {
      try {
        final blob = await _ref
            .read(cacheCryptoProvider)
            .seal(png, req.cacheSecret);
        final dir = await _ensureDir();
        await File(
          '${dir.path}/${req.cacheKey}.bin',
        ).writeAsBytes(blob, flush: true);
      } catch (_) {
        // cache write best-effort
      }
    }
    return png;
  }

  Future<Uint8List?> _fetchAndDecodeImage(ThumbRequest req) async {
    try {
      final resp = await http
          .get(Uri.parse(req.url), headers: req.headers)
          .timeout(const Duration(seconds: 20));
      if (resp.statusCode < 200 || resp.statusCode >= 300) return null;
      final png = await _downscale(resp.bodyBytes, req.size);
      // Fetch succeeded but the bytes won't decode — permanent, not transient.
      // Mark it so retries + re-mounts stop re-downloading the original.
      if (png == null) _undecodable.add(req.cacheKey);
      return png;
    } catch (_) {
      return null;
    }
  }

  /// Capture a video keyframe, downscaled to [ThumbRequest.size]. Null on any
  /// failure (→ kind icon), and null too for a frame with no picture in it:
  /// caching a black rectangle would look like a broken thumbnail forever.
  Future<Uint8List?> _captureVideoFrame(ThumbRequest req) async {
    final png = Platform.isAndroid
        ? await _captureVideoFrameAndroid(req)
        : await _captureVideoFrameMpv(req);
    if (png == null) return null;
    if (await _looksBlank(png)) {
      // Decoded fine, but there's no picture in it. That's a property of the
      // file, not a transient miss, so record it like an undecodable image —
      // otherwise every scroll re-runs the whole capture for nothing.
      _undecodable.add(req.cacheKey);
      return null;
    }
    return png;
  }

  /// Android capture: hand the URL to the platform's own frame grabber.
  /// libmpv can't do it here — see [androidVideoThumbnail].
  Future<Uint8List?> _captureVideoFrameAndroid(ThumbRequest req) async {
    try {
      final raw = await androidVideoThumbnail(
        req.url,
        req.headers,
        req.size,
      ).timeout(_videoFirstFrameTimeout);
      if (raw == null) return null;
      // Awaited, not returned bare: an unawaited return escapes this catch.
      return await _downscale(raw, req.size);
    } catch (_) {
      // Includes the timeout: a remote too slow to yield a frame in budget.
      return null;
    }
  }

  /// Desktop/iOS capture via libmpv. A [VideoController] must be attached (and
  /// a frame actually rendered) for `screenshot` to return pixels, so we create
  /// one, play muted until the first frame renders, then grab it.
  ///
  /// If that frame turns out to be blank — a fade-in, a slate, a camera warming
  /// up — we seek a little way in and grab once more, rather than handing back
  /// a black tile. Whatever comes out still faces [_captureVideoFrame]'s guard;
  /// the check here only decides whether the seek is worth doing.
  Future<Uint8List?> _captureVideoFrameMpv(ThumbRequest req) async {
    Player? player;
    try {
      player = Player();
      // Attach an off-screen video output so libmpv decodes + renders frames.
      final controller = VideoController(player);
      await player.setVolume(0);
      await player.open(Media(req.url, httpHeaders: req.headers), play: true);
      await controller.waitUntilFirstFrameRendered.timeout(
        _videoFirstFrameTimeout,
      );
      await player.pause();
      final first = await _screenshot(player, req.size);
      if (first != null && !await _looksBlank(first)) return first;

      // Nothing in that frame: try one further in (10% of the run, capped, so
      // a two-hour film doesn't land on an ad break's worth of black).
      final duration = player.state.duration;
      if (duration > Duration.zero) {
        final at = Duration(
          milliseconds: (duration.inMilliseconds ~/ 10).clamp(500, 10000),
        );
        if (at < duration) {
          await player.seek(at);
          // The seeked frame has to reach the video output before it can be
          // grabbed; there is no "frame ready" signal to await after a seek.
          await Future<void>.delayed(const Duration(milliseconds: 400));
          final second = await _screenshot(player, req.size);
          if (second != null) return second;
        }
      }
      return first;
    } catch (_) {
      return null;
    } finally {
      try {
        await player?.dispose();
      } catch (_) {
        // already disposed / never constructed
      }
    }
  }

  /// One `screenshot` grab, downscaled. Null if libmpv has no frame to give.
  Future<Uint8List?> _screenshot(Player player, int size) async {
    final raw = await player
        .screenshot(format: 'image/png')
        .timeout(const Duration(seconds: 6));
    if (raw == null) return null;
    return _downscale(raw, size);
  }

  /// True when [png] holds no picture — a black leader, or a frame that never
  /// decoded. Cheap: the bytes are already downscaled to thumbnail size by the
  /// time we look. Undecodable input counts as "not blank" so a frame we
  /// simply can't inspect is never thrown away.
  Future<bool> _looksBlank(Uint8List png) async {
    ui.Codec? codec;
    try {
      codec = await ui.instantiateImageCodec(png);
      final frame = await codec.getNextFrame();
      final data = await frame.image.toByteData(
        format: ui.ImageByteFormat.rawRgba,
      );
      frame.image.dispose();
      if (data == null) return false;
      return isFlatRgba(data.buffer.asUint8List());
    } catch (_) {
      return false;
    } finally {
      codec?.dispose();
    }
  }

  /// Downscale [bytes] to [size] px wide PNG. No caching (the caller seals/writes).
  Future<Uint8List?> _downscale(Uint8List bytes, int size) async {
    try {
      final codec = await ui.instantiateImageCodec(bytes, targetWidth: size);
      final frame = await codec.getNextFrame();
      final data = await frame.image.toByteData(format: ui.ImageByteFormat.png);
      return data?.buffer.asUint8List();
    } catch (_) {
      return null;
    }
  }

  Future<Directory> _ensureDir() async {
    final cached = _cacheDir;
    if (cached != null) return cached;
    Directory base;
    try {
      base = await getApplicationCacheDirectory();
    } catch (_) {
      base = await getTemporaryDirectory();
    }
    final dir = Directory('${base.path}/airclone_thumbs');
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    _cacheDir = dir;
    return dir;
  }

  Future<void> _acquire() async {
    if (_active < _maxConcurrent) {
      _active++;
      return;
    }
    final c = Completer<void>();
    _waiters.add(c);
    await c.future;
    _active++;
  }

  Future<void> _acquireVideo() async {
    if (_activeVideo < _maxConcurrentVideo) {
      _activeVideo++;
      return;
    }
    final c = Completer<void>();
    _videoWaiters.add(c);
    await c.future;
    _activeVideo++;
  }

  void _releaseVideo() {
    _activeVideo--;
    if (_videoWaiters.isNotEmpty) {
      final c = _videoWaiters.removeAt(0);
      if (!c.isCompleted) c.complete();
    }
  }

  void _release() {
    _active--;
    if (_waiters.isNotEmpty) {
      final c = _waiters.removeAt(0);
      if (!c.isCompleted) c.complete();
    }
  }
}

/// Provides the singleton [ThumbnailService].
final thumbnailServiceProvider = Provider<ThumbnailService>(
  (ref) => ThumbnailService(ref),
);
