import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:airclone/src/update/minisign.dart';
import 'package:flutter_test/flutter_test.dart';

/// Verifying a release signature.
///
/// This is the only thing standing between a downloaded file and Airclone
/// running it, on Linux especially: Windows has Authenticode and macOS has
/// Developer ID, but a `.AppImage` or a `.tar.gz` carries no opinion of its own
/// about who made it.
///
/// The fixtures are NOT written by this code. `dev/update/make-test-fixture.py`
/// builds them in Python, with a different Ed25519 implementation, and CI runs
/// the real `minisign -V` over the same files. Three implementations have to
/// agree before a pass here means anything - a fixture generated by the code
/// under test would only prove the code agrees with itself.
void main() {
  final dir = Directory('test/fixtures/update');
  final manifest = File('${dir.path}/SHA256SUMS').readAsBytesSync();
  final signature = File('${dir.path}/SHA256SUMS.minisig').readAsStringSync();
  final tampered = File('${dir.path}/SHA256SUMS.tampered').readAsBytesSync();
  final keyLine = File('${dir.path}/public_key.txt').readAsStringSync().trim();
  final key = MinisignPublicKey.parse(keyLine)!;

  group('the public key', () {
    test('parses into a key id and 32 bytes', () {
      expect(key.keyId.length, 8);
      expect(key.bytes.length, 32);
    });

    /// A fork that has not set a key, or a mangled build-time define, must end
    /// with updates refused - never a crash, and never a key of the wrong size
    /// reaching the verifier.
    test('refuses anything that is not one', () {
      expect(MinisignPublicKey.parse(''), isNull);
      expect(MinisignPublicKey.parse('not base64 at all !!'), isNull);
      expect(
        MinisignPublicKey.parse(base64.encode(List.filled(41, 7))),
        isNull,
      );
      // Right length, wrong algorithm tag.
      expect(
        MinisignPublicKey.parse(
          base64.encode([0x58, 0x58, ...List.filled(40, 1)]),
        ),
        isNull,
      );
    });
  });

  group('a good signature', () {
    test('is trusted, and hands back the comment it signed', () async {
      final result = await verifyMinisign(
        payload: manifest,
        signatureText: signature,
        trusted: [key],
      );
      expect(result.ok, isTrue, reason: 'refused: ${result.refusal}');
      expect(result.trustedComment, contains('airclone'));
      expect(result.trustedComment, contains('v9.9.9'));
    });

    /// Key rotation: during a changeover the release carries signatures from
    /// both keys and a client that knows either must still update.
    test('is found among several trusted keys', () async {
      final other = MinisignPublicKey.parse(
        base64.encode([
          0x45,
          0x64,
          ...List.filled(8, 9),
          ...List.filled(32, 3),
        ]),
      )!;
      final result = await verifyMinisign(
        payload: manifest,
        signatureText: signature,
        trusted: [other, key],
      );
      expect(result.ok, isTrue);
    });
  });

  group('what must be refused', () {
    Future<MinisignRefusal?> refusalFor({
      List<int>? payload,
      String? text,
      List<MinisignPublicKey>? keys,
    }) async => (await verifyMinisign(
      payload: payload ?? manifest,
      signatureText: text ?? signature,
      trusted: keys ?? [key],
    )).refusal;

    /// One byte of one hash changed - the whole point of the exercise.
    test('a tampered manifest', () async {
      expect(
        await refusalFor(payload: tampered),
        MinisignRefusal.payloadMismatch,
      );
    });

    /// A real signature with someone else's comment on it. The comment carries
    /// the release tag, so accepting this would let an old release be replayed
    /// as a new one.
    test('a trusted comment that was edited after signing', () async {
      final edited = signature.replaceFirst('v9.9.9', 'v9.9.8');
      expect(await refusalFor(text: edited), MinisignRefusal.commentMismatch);
    });

    test('a key this build does not trust', () async {
      expect(await refusalFor(keys: const []), MinisignRefusal.wrongKey);
      final stranger = MinisignPublicKey.parse(
        base64.encode([
          0x45,
          0x64,
          ...List.filled(8, 9),
          ...List.filled(32, 3),
        ]),
      )!;
      expect(await refusalFor(keys: [stranger]), MinisignRefusal.wrongKey);
    });

    /// The right key id with the wrong key bytes: a forger who knows which key
    /// we trust still cannot sign for it.
    test('the right key id over the wrong key', () async {
      final impostor = MinisignPublicKey(
        keyId: key.keyId,
        bytes: key.bytes.map((b) => b ^ 0xff).toList().asUint8List(),
      );
      expect(
        await refusalFor(keys: [impostor]),
        MinisignRefusal.payloadMismatch,
      );
    });

    test('a file that is not a signature', () async {
      expect(await refusalFor(text: ''), MinisignRefusal.malformed);
      expect(await refusalFor(text: 'hello'), MinisignRefusal.malformed);
      expect(
        await refusalFor(text: signature.split('\n').take(2).join('\n')),
        MinisignRefusal.malformed,
      );
    });

    test('base64 that decodes to the wrong size', () async {
      final lines = signature.split('\n');
      lines[1] = base64.encode(List.filled(40, 1));
      expect(
        await refusalFor(text: lines.join('\n')),
        MinisignRefusal.malformed,
      );
    });

    /// An algorithm we do not implement must be refused, not guessed at.
    test('an unknown algorithm tag', () async {
      final sig = parseMinisignSignature(signature)!;
      final lines = signature.split('\n');
      lines[1] = base64.encode([
        0x58, 0x58, // "XX"
        ...sig.keyId,
        ...sig.signature,
      ]);
      expect(
        await refusalFor(text: lines.join('\n')),
        MinisignRefusal.malformed,
      );
    });
  });

  group('parsing', () {
    test('reads the algorithm, the key id and both signatures', () {
      final sig = parseMinisignSignature(signature)!;
      expect(sig.prehashed, isTrue, reason: 'the fixture is the ED variant');
      expect(sig.keyId.length, 8);
      expect(sig.signature.length, 64);
      expect(sig.globalSignature.length, 64);
      expect(sig.trustedComment, isNotEmpty);
    });

    /// Files come back from a shell, an editor or an HTTP body with a trailing
    /// newline or two; that is not a reason to refuse a genuine release.
    test('tolerates trailing blank lines', () {
      expect(parseMinisignSignature('$signature\n\n'), isNotNull);
    });

    test('refuses a fifth line of content', () {
      expect(parseMinisignSignature('${signature}extra\n'), isNull);
    });
  });
}

extension on List<int> {
  /// Small helper so a test can flip bytes and still hand over a Uint8List.
  Uint8List asUint8List() => Uint8List.fromList(this);
}
